- path: '/devices'
  method: GET
  summary: Get information about all your devices.
  examples:
    - description: Get information about all devices.
      responseCode: 200
      responseBody:
        - id: "foobar"
          label: "My cloudBit"
          subscribers: []
          subscriptions: []
          user_id: "1"
          wifi: {}

- path: '/devices/{device_id}'
  method: POST
  summary: Create a device in the database and associate it with the user. User is known through the `access_token` being used.
  examples:
    - description: Any field `PUT` accepts may be used here.
      requestBody:
        label: Water my plants
      responseBody:
        id: a84hf038ierj
        label: Water my plants
        subscribers: []
        subscriptions: []
        user_id: "1"
        wifi: {}

- path: '/devices/{device_id}'
  method: GET
  summary: Get device information and current settings.

- path: '/devices/{device_id}'
  method: PUT
  summary: Update device settings.

- path: '/devices/{device_id}'
  method: DELETE
  summary: Remove device from database, dissaociating user.

- path: '/devices/{device_id}/output'
  method: POST
  summary: Write amplitude to device output.
  bodyParams:
    - name: percent
      summary: What percentage of amplitude to write
      required: false
      default: 100
      type: Integer
    - name: duration_ms
      type: Integer
      summary: Sustain the given output percentage for n milliseconds.
      required: false
      default: 3000

- path: '/devices/{device_id}/input'
  method: GET
  summary: Read stream of amplitude from device input.
  bodyParams: []

- path: '/subscriptions'
  method: POST
  summary: Create a subscription
  bodyParams:
    - name: subscriber_id
      summary: A device ID or URI.
    - name: publisher_id
      summary: A device ID
    - name: publisher_events
      summary: What types of events do you want the subscriber to receive?

- path: '/subscriptions'
  method: GET
  summary: Get the subscriptions, subscribers, or both of a device or registerd callback.

- path: '/subscriptions'
  method: DELETE
  summary: Delete either a subscription between devices or a registered callback.
