- path: '/devices/{device_id}/output'
  method: POST
  summary: Write amplitude to device output. This endpoint always returns 200 "OK" regardless of if the device is actually connected.
  bodyParams:
    - name: percent
      summary: What percentage of amplitude to write
      required: false
      default: 100
      type: Integer
    - name: duration_ms
      type: Integer
      summary: Sustain the given output percentage for n milliseconds.
      required: false
      default: 3000
  examples:
    - description: 'By default maximum amplitude is sent for 3 seconds:'
      responseBody: OK
    - description: 'This outputs 10% amplitude for 10 seconds:'
      requestBody:
        percent: 10
        duration_ms: 10000
      responseBody: OK



- path: '/devices/{device_id}/input'
  method: GET
  summary: Read a stream of amplitude from device input. This requires that your HTTP Client supports Server Sent Events (SSE).
  bodyParams: []
  examples:
    - description: "Unlike the typical HTTP request/response cycle, SSE works such that the server response is an open pipe sending data at will. The response below shows what one data even contains:"
      responseBody:
        type: input
        timestamp: 1416007639847
        percent: 38
        from:
          user:
            id: 1
          device:
            id: a
            ap:
              ssid: littlebitsTC
              strength: 4
              mac: ab:12:cd:34:ef:56



- path: '/devices'
  method: GET
  summary: ''
  examples:
    - description: "Get information about all devices:"
      responseBody:
        - id: a84hf038ierj
          label: My cloudBit
          subscribers: []
          subscriptions: []
          user_id: 1
          wifi: {}


- path: '/devices/{device_id}'
  method: POST
  summary: Create a device in the database and associate it with the user.
  examples:
    - description: "Any field `PUT` accepts may be used here:"
      requestBody:
        label: Water my plants
      responseBody:
        id: a84hf038ierj
        label: Water my plants
        subscribers: []
        subscriptions: []
        user_id: 1
        wifi: {}



- path: '/devices/{device_id}'
  method: GET
  summary: ''
  examples:
    - description: "Get device information and current settings:"
      responseBody:
        id: a84hf038ierj
        label: My cloudBit
        subscribers: []
        subscriptions: []
        user_id: 1
        wifi: {}



- path: '/devices/{device_id}'
  method: PUT
  summary: ''
  examples:
    - description: "Update device settings:"
      requestBody:
        label: Door Bell
      responseBody:
        id: a84hf038ierj
        label: Door Bell
        subscribers: []
        subscriptions: []
        user_id: 1
        wifi: {}



- path: '/devices/{device_id}'
  method: DELETE
  summary: Remove device record from database, including user association.




- path: '/subscriptions'
  method: POST
  summary: Create a subscription
  bodyParams:
    - name: subscriber_id
      summary: A device ID or URI.
    - name: publisher_id
      summary: A device ID
    - name: publisher_events
      # Beware if editing, the white-space is rendered literally. In a mono-font
      # it appears ragged but in the browser seems to look good. This is a poor-man's
      # solution until we have better layout fields.
      summary: |
        What types of events do you want the subscriber to receive? The allowed values are:

        amplitude                         anything (default)
        amplitude:delta:ignite       significant jump
        amplitude:delta:release    significant drop
        amplitude:level:active       high voltage
        amplitude:level:idle           low voltage
  examples:
    - descripton: 'Make a device `a84hf038ierj` receive anything published by `bu1tei32i9r9`:'
      requestBody:
        subscriber_id: a84hf038ierj
        publisher_id: bu1tei32i9r9
        publisher_events: ['amplitude:delta:ignite']
      responseBody:
        subscriber_id: a84hf038ierj
        publisher_id: bu1tei32i9r9
        publisher_events:
          - name: "amplitude:delta:ignite"




- path: '/subscriptions'
  method: GET
  summary: Get the subscriptions, subscribers, or both of a device or registerd callback.
  queryParams:
    - name: subscriber_id
      summary: A device ID or URI. This limits the result to only subscriptions where this ID is the subscriber.
    - name: publisher_id
      summary: A device ID. This limits the result to only subscriptions where this ID is the publisher.
  examples:
    - description: 'Get everything that follows this device (this may return device IDs OR URIs):'
      requestQuery:
        publisher_id: bu1tei32i9r9
      responseBody:
        - subscriber_id: a84hf038ierj
          publisher_id: bu1tei32i9r9
          publisher_events:
            - name: 'amplitude:delta:ignite'
    - description: 'Get everything that this device follows (this may ONLY return device IDs).'
      requestQuery:
        subscriber_id: a84hf038ierj
      responseBody:
        - subscriber_id: a84hf038ierj
          publisher_id: bu1tei32i9r9
          publisher_events:
            - name: "amplitude:delta:ignite"



- path: '/subscriptions'
  method: DELETE
  summary: Delete a subscription. subscriber_id AND publisher_id are required.
  bodyParams:
    - name: subscriber_id
      summary: A device ID or URI.
      required: true
    - name: publisher_id
      summary: A device ID.
      required: true
  examples:
    - description: ''
      requestBody:
        subscriber_id: a84hf038ierj
        publisher_id: bu1tei32i9r9
      responseBody: OK
