apiVersion: v1
kind: ReplicationController
metadata:
  name: www-developers
  labels:
    app: www-developers
    version: 0.2.0-rc1
spec:
  template:
    metadata:
      name: www-developers
      labels:
        app: www-developers
        version: 0.2.0-rc1
    spec:
      containers:
        - name: www-developers
          image: gcr.io/littlebits-electronics/www-developers:v0.2.0-rc1
          ports:
            - name: www-developers
              containerPort: 80
          env:
            - name: PORT
              value: '80'
