apiVersion: v1
kind: Service
metadata:
  name: www-developers
  labels:
    app: www-developers
spec:
  type: LoadBalancer
  selector:
    app: www-developers
  ports:
    - port: 80
      targetPort: www-developers
